### ISSUE TITLE
KeyError: 'max_cardinality'

### ISSUE THREAD

**Issue by evanphilip** [watermarkhu/qsurface#35]
I am trying to run the following from the example:
from qsurface.main import initialize, run, BenchmarkDecoder
code, decoder = initialize((6,6), "toric", "mwpm", enabled_errors=["pauli"])
run(code, decoder, iterations=10, error_rates = {"p_bitflip": 0.1})

I am getting the following error: 
KeyError                                  Traceback (most recent call last)
<ipython-input-1-03436fecdacc> in <module>
......
in match_syndromes(self, syndromes, use_blossomv, **kwargs)
     60         matching = matching_graph(
     61             edges,
---> 62             maxcardinality=self.config["max_cardinality"],
     63             num_nodes=len(syndromes),
     64             **kwargs,

KeyError: 'max_cardinality'

I have made sure I am on the same version of python as the one in the hub online example, which runs without issues.

=====UPDATE=====

I discovered that the cause of this error is the missing *.ini files when installing with pip.

**Comment by watermarkhu** [comment]
It seems that the decoders.ini file is not packaged even though it is specified in manifest.in.

**Comment by watermarkhu** [comment]
Fixed in #36. 

I've repackaged it in version 0.1.5. You can update qsurface via `pip install --upgrade qsurface`.

**Comment by evanphilip** [comment]
Thank you very much! Really appreciate your work.
